=== NetBeansDay/PCTMonitor/Libraries/java/maven/MoonsIT/PCT/src/main/java/uk/co/moons/xml/layers/Layers.xsd
<?xml version="1.0" encoding="windows-1252"?>
<!--
  This software is the property of Moon's Information Technology Ltd.
 
  All rights reserved.
 
  The software is only to be used for development and research purposes.
  Commercial use is only permitted under license or agreement.
 
  Copyright (C)  Moon's Information Technology Ltd.
  
  Author: rupert@moonsit.co.uk
 
 
-->

<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://uk.co.moons.pct/schema/Layers"
    xmlns:tns="http://uk.co.moons.pct/schema/Layers"
    elementFormDefault="qualified">
    <xsd:element name="Layers">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="OrderedControllers" minOccurs="0">
                    <xsd:complexType>
                        <xsd:sequence>
                            <xsd:element name="Controller" type="xsd:string" maxOccurs="unbounded"/>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="Type" type="xsd:string" ></xsd:element>
                <xsd:element name="Description" type="xsd:string" maxOccurs="1" minOccurs="0" ></xsd:element>
                <xsd:element name="Layer" maxOccurs="unbounded">
                    <xsd:complexType>
                        <xsd:sequence>
                            <!--<xsd:element name="Type" type="xsd:string"></xsd:element>-->
                            <xsd:element name="Name" type="xsd:string"></xsd:element>
                            <xsd:element name="Controller" maxOccurs="unbounded">
                                <xsd:complexType>
                                    <xsd:sequence>
                                        <!--<xsd:element name="Type" type="xsd:string"></xsd:element>-->
                                        <xsd:element name="Name" type="xsd:string"></xsd:element>
                                        <xsd:element name="Activation" type="tns:Activation" minOccurs="0"></xsd:element>

                                        <xsd:element name="Functions">
                                            <xsd:complexType>
                                                <xsd:sequence>
                                                    <xsd:element name="InputFunctions" minOccurs="0" maxOccurs="1">
                                                        <xsd:complexType>
                                                            <xsd:sequence>
                                                                <xsd:element name="Input" type="tns:ControlFunction"></xsd:element>
                                                                <xsd:element name="Transfers" maxOccurs="1" minOccurs="0">
                                                                    <xsd:complexType>
                                                                        <xsd:sequence>
                                                                            <xsd:element name="Transfer"  type="tns:ControlFunction"  minOccurs="0" maxOccurs="unbounded"></xsd:element>
                                                                        </xsd:sequence>
                                                                    </xsd:complexType>
                                                                </xsd:element>
                                                            </xsd:sequence>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                    <xsd:element name="ReferenceFunctions" minOccurs="0" maxOccurs="1">
                                                        <xsd:complexType>
                                                            <xsd:sequence>
                                                                <xsd:element name="Reference" type="tns:ControlFunction"></xsd:element>
                                                                <xsd:element name="Transfers" maxOccurs="1" minOccurs="0">
                                                                    <xsd:complexType>
                                                                        <xsd:sequence>
                                                                            <xsd:element name="Transfer"  type="tns:ControlFunction" minOccurs="0" maxOccurs="unbounded"></xsd:element>
                                                                        </xsd:sequence>
                                                                    </xsd:complexType>
                                                                </xsd:element>
                                                            </xsd:sequence>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                    <xsd:element name="ErrorFunctions" minOccurs="0" maxOccurs="1">
                                                        <xsd:complexType>
                                                            <xsd:sequence>
                                                                <xsd:element name="Error" type="tns:ControlFunction"></xsd:element>
                                                                <xsd:element name="Transfers" maxOccurs="1" minOccurs="0">
                                                                    <xsd:complexType>
                                                                        <xsd:sequence>
                                                                            <xsd:element name="Transfer"  type="tns:ControlFunction"  minOccurs="0" maxOccurs="unbounded"></xsd:element>
                                                                        </xsd:sequence>
                                                                    </xsd:complexType>
                                                                </xsd:element>
                                                            </xsd:sequence>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                    <xsd:element name="OutputFunctions" minOccurs="0" maxOccurs="1">
                                                        <xsd:complexType>
                                                            <xsd:sequence>
                                                                <xsd:element name="Output" type="tns:ControlFunction"></xsd:element>
                                                                <xsd:element name="Transfers" maxOccurs="1" minOccurs="0">
                                                                    <xsd:complexType>
                                                                        <xsd:sequence>
                                                                            <xsd:element name="Transfer"  type="tns:ControlFunction" minOccurs="0" maxOccurs="unbounded"></xsd:element>
                                                                        </xsd:sequence>
                                                                    </xsd:complexType>
                                                                </xsd:element>
                                                            </xsd:sequence>
                                                        </xsd:complexType>
                                                    </xsd:element>
                                                </xsd:sequence>
                                            </xsd:complexType>
                                        </xsd:element>
                                    </xsd:sequence>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:sequence>
                    </xsd:complexType>
                </xsd:element>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>



    <xsd:complexType  name="ControlFunction">
        <xsd:sequence>
            <xsd:element name="Name" type="xsd:string"></xsd:element>
            <xsd:element name="Description" type="xsd:string"></xsd:element>
            <xsd:element name="NeuralFunction" type="tns:NeuralFunction" ></xsd:element>

        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Parameters" >
        <xsd:sequence>
            <xsd:element name="Name" type="xsd:string"></xsd:element>
            <xsd:element name="Value" type="xsd:string"></xsd:element>
            <xsd:element name="DataType" type="xsd:string"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="NeuralFunction">
        <xsd:sequence>
            <xsd:element name="Type" type="xsd:string"></xsd:element>
            <xsd:element name="Parameters" type="tns:Parameters" minOccurs="0" maxOccurs="unbounded"></xsd:element>
            <xsd:element name="Links" type="tns:Link" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="Link">
        <xsd:sequence>
            <xsd:element name="Index"  type="xsd:string"/>
            <xsd:element name="Name"  type="xsd:string"/>
            <xsd:element name="Type"  type="xsd:string" minOccurs="0" maxOccurs="1"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="Activation">
        <xsd:sequence>
            <xsd:element name="DeactivateLink" type="tns:Link"></xsd:element>
            <xsd:element name="Functions" minOccurs="0">
                <xsd:complexType>
                    <xsd:sequence>
                        <xsd:element name="List">
                            <xsd:complexType>
                                <xsd:sequence>
                                    <xsd:element name="FunctionType" minOccurs="1" maxOccurs="unbounded" type="xsd:string"></xsd:element>
                                </xsd:sequence>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:sequence>
                </xsd:complexType>
            </xsd:element>
        </xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== NetBeansDay/PCTMonitor/Controllers/Models/PRGUI/GUITest009_OverideOutput.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Layers xmlns="http://uk.co.moons.pct/schema/Layers" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://uk.co.moons.pct/schema/Layers ../Layers.xsd">
    <Type>Model</Type>
    <Layer>
        <Name>Interface</Name>
        <Controller>
            <Name>Atom</Name>
            <Functions>
                <InputFunctions>
                    <Input>
                        <Name>AtomInput</Name>
                        <Description>...</Description>
                        <NeuralFunction>
                            <Type>SineGenerator</Type>
                            <Parameters>
                                <Name>Amplitude</Name>
                                <Value>1</Value>
                                <DataType>Double</DataType>
                            </Parameters>
                            <Parameters>
                                <Name>Frequency</Name>
                                <Value>1</Value>
                                <DataType>Double</DataType>
                            </Parameters>
                            <Parameters>
                                <Name>Phase</Name>
                                <Value>0</Value>
                                <DataType>Double</DataType>
                            </Parameters>
                            <Parameters>
                                <Name>XShift</Name>
                                <Value>0</Value>
                                <DataType>Double</DataType>
                            </Parameters>
                            <Parameters>
                                <Name>YShift</Name>
                                <Value>0</Value>
                                <DataType>Double</DataType>
                            </Parameters>
                            <Parameters>
                                <Name>Step</Name>
                                <Value>1</Value>
                                <DataType>Double</DataType>
                            </Parameters>
                            <Links>
                                <Index>0</Index>
                                <Name>Pause</Name>
                            </Links>
                        </NeuralFunction>
                    </Input>
                    <Transfers>
                        <Transfer>
                            <Name>Pause</Name>
                            <Description>...</Description>
                            <NeuralFunction>
                                <Type>Pause</Type>
                                <Parameters>
                                    <Name>ConstantRate</Name>
                                    <Value>true</Value>
                                    <DataType>Boolean</DataType>
                                </Parameters>
                                <Parameters>
                                    <Name>Pause</Name>
                                    <Value>50</Value>
                                    <DataType>Double</DataType>
                                </Parameters>
                            </NeuralFunction>
                        </Transfer>
                    </Transfers>
                </InputFunctions>
                <ReferenceFunctions>
                    <Reference>
                        <Name>AtomReference</Name>
                        <Description>...</Description>
                        <NeuralFunction>
                            <Type>Constant</Type>
                            <Parameters>
                                <Name>Constant</Name>
                                <Value>20</Value>
                                <DataType>Double</DataType>
                            </Parameters>
                        </NeuralFunction>
                    </Reference>
                </ReferenceFunctions>
                <ErrorFunctions>
                    <Error>
                        <Name>AtomError</Name>
                        <Description>...</Description>
                        <NeuralFunction>
                            <Type>Subtract</Type>
                            <Links>
                                <Index>0</Index>
                                <Name>AtomReference</Name>
                            </Links>
                            <Links>
                                <Index>1</Index>
                                <Name>AtomInput</Name>
                            </Links>
                        </NeuralFunction>
                    </Error>
                </ErrorFunctions>
                <OutputFunctions>
                    <Output>
                        <Name>AtomOutput</Name>
                        <Description>...</Description>
                        <NeuralFunction>
                            <Type>Constant</Type>
                            <Parameters>
                                <Name>Constant</Name>
                                <Value>20</Value>
                                <DataType>Double</DataType>
                            </Parameters>
                            <Links>
                                <Index>0</Index>
                                <Name>AtomReference</Name>
                            </Links>
                            <Links>
                                <Index>1</Index>
                                <Name>AtomError</Name>
                            </Links>
                        </NeuralFunction>
                    </Output>
                    <Transfers>
                        <Transfer>
                            <Name>TwoConstant</Name>
                            <Description>...</Description>
                            <NeuralFunction>
                                <Type>Constant</Type>
                                <Parameters>
                                    <Name>Constant</Name>
                                    <Value>20</Value>
                                    <DataType>Double</DataType>
                                </Parameters>
                                <Links>
                                    <Index>0</Index>
                                    <Name>AtomOutput</Name>
                                </Links>
                                <Links>
                                    <Index>1</Index>
                                    <Name>Pause</Name>
                                </Links>
                            </NeuralFunction>
                        </Transfer>
                    </Transfers>
                </OutputFunctions>
            </Functions>
        </Controller>
    </Layer>
</Layers>

=== NetBeansDay/PCTMonitor/Controllers/Models/PRGUI/GUITest005_Loopback.valid.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Layers xmlns="http://uk.co.moons.pct/schema/Layers" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://uk.co.moons.pct/schema/Layers ../Layers.xsd">
    <Type>Model</Type>
    <Layer>
        <Name>Interface</Name>
        <Controller>
            <Name>One</Name>
            <Functions>
                <InputFunctions>
                    <Input>
                        <Name>OneInput</Name>
                        <Description>...</Description>
                        <NeuralFunction>
                            <Type>PassThrough</Type>
                            <Links>
<Index>0</Index>
<Name>OneOutput</Name>
                            </Links>
                        </NeuralFunction>
                    </Input>
                </InputFunctions>
                <OutputFunctions>
                    <Output>
                        <Name>OneOutput</Name>
                        <Description>...</Description>
                        <NeuralFunction>
                            <Type>Constant</Type>
                            <Parameters>
<Name>Constant</Name>
<Value>100</Value>
<DataType>Double</DataType>
                            </Parameters>
                        </NeuralFunction>
                    </Output>
                </OutputFunctions>
            </Functions>
        </Controller>
    </Layer>
</Layers>

=== NetBeansDay/PCTMonitor/Libraries/java/maven/MoonsIT/RobotControl/src/main/java/uk/co/moons/xml/layers/input/OneMotorConfig.xml
<?xml version="1.0" encoding="windows-1252"?>
<!--
  This software is the property of Moon's Information Technology Ltd.
 
  All rights reserved.
 
  The software is only to be used for development and research purposes.
  Commercial use is only permitted under license or agreement.
 
  Copyright (C)  Moon's Information Technology Ltd.
  
  Author: rupert@moonsit.co.uk
 
 
-->

<ns1:Layers  xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
   xmlns:ns1='http://uk.co.moons.pct/schema/Layers'
   xsi:schemaLocation='http://uk.co.moons.pct/schema/Layers ../../../../../../../../PCT/src/uk/co/moons/xml/layers/Layers.xsd'>
    <ns1:Layer>
        <ns1:Type>Motors</ns1:Type>
        <ns1:Name>Robot Motors</ns1:Name>
        <ns1:Controller>
            <ns1:Type>Motor</ns1:Type>
            <ns1:Name>Motor B</ns1:Name>
            <ns1:Functions>
                <ns1:Input>
                    <ns1:Type>MotorInput</ns1:Type>
                    <ns1:Name>MotorBInput</ns1:Name>
                    <ns1:NeuralFunction>
                        <ns1:Type>MotorRead</ns1:Type>
                        <ns1:Name>Motor B</ns1:Name>
                        <ns1:Parameters>
                            <ns1:Name>MotorIndex</ns1:Name>
                            <ns1:Value>B</ns1:Value>
                            <ns1:DataType>Motor</ns1:DataType>
                        </ns1:Parameters>
                        <ns1:Parameters>
                            <ns1:Name>Smoothness</ns1:Name>
                            <ns1:Value>0.1</ns1:Value>
                            <ns1:DataType>Double</ns1:DataType>
                        </ns1:Parameters>
                    </ns1:NeuralFunction>
                </ns1:Input>
                <ns1:Reference>
                    <ns1:Type>Constant</ns1:Type>
                    <ns1:Name>SpeedReferenceB</ns1:Name>
                    <ns1:NeuralFunction>
                        <ns1:Type>Constant</ns1:Type>
                        <ns1:Name>Speed</ns1:Name>
                        <ns1:Parameters>
                            <ns1:Name>Constant</ns1:Name>
                            <ns1:Value>900</ns1:Value>
                            <ns1:DataType>Double</ns1:DataType>
                        </ns1:Parameters>
                    </ns1:NeuralFunction>
                </ns1:Reference>
                <ns1:Error>
                    <ns1:Type>Error</ns1:Type>
                    <ns1:Name>MotorBError</ns1:Name>
                    <ns1:NeuralFunction>
                        <ns1:Type>Subtract</ns1:Type>
                        <ns1:Name>MotorBError</ns1:Name>
                    </ns1:NeuralFunction>
                </ns1:Error>
                <ns1:Output>
                    <ns1:Type>MotorOutput</ns1:Type>
                    <ns1:Name>MotorBOutput</ns1:Name>
                    <ns1:NeuralFunction>
                        <ns1:Type>MotorWrite</ns1:Type>
                        <ns1:Name></ns1:Name>
                        <ns1:Parameters>
                            <ns1:Name>Gain</ns1:Name>
                            <ns1:Value>10</ns1:Value>
                            <ns1:DataType>Double</ns1:DataType>
                        </ns1:Parameters>
                        <ns1:Parameters>
                            <ns1:Name>Slow</ns1:Name>
                            <ns1:Value>0.01</ns1:Value>
                            <ns1:DataType>Double</ns1:DataType>
                        </ns1:Parameters>
                        <ns1:Parameters>
                            <ns1:Name>MotorIndex</ns1:Name>
                            <ns1:Value>B</ns1:Value>
                            <ns1:DataType>Motor</ns1:DataType>
                        </ns1:Parameters>
                    </ns1:NeuralFunction>
                </ns1:Output>
            </ns1:Functions>
        </ns1:Controller>      
    </ns1:Layer>
</ns1:Layers>

=== NetBeansDay/PCTMonitor/Controllers/Models/PRGUI/DesignTest.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Layers xmlns="http://uk.co.moons.pct/schema/Layers" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://uk.co.moons.pct/schema/Layers ../Layers.xsd">
    <Type>Model</Type>
    <Layer>
        <Name>Interface</Name>
        <Controller>
            <Name>AtomOffset</Name>
            <Functions>
                <InputFunctions>
                    <Input>
                        <Name>AtomOffsetInput</Name>
                        <Description>...</Description>
                        <NeuralFunction>
                            <Type>Proportional</Type>
                            <Parameters>
<Name>Gain</Name>
<Value>120</Value>
<DataType>Double</DataType>
                            </Parameters>
                            <Links>
<Index>0</Index>
<Name>Sum</Name>
                            </Links>
                        </NeuralFunction>
                    </Input>
                    <Transfers>
                        <Transfer>
                            <Name>Sum</Name>
                            <Description>...</Description>
                            <NeuralFunction>
<Type>WeightedSum</Type>
<Parameters>
    <Name>Weights</Name>
    <Value>1,1</Value>
    <DataType>Double</DataType>
</Parameters>
<Links>
    <Index>0</Index>
    <Name>TenConstant</Name>
</Links>
<Links>
    <Index>1</Index>
    <Name>TwentyConstant</Name>
</Links>
                            </NeuralFunction>
                        </Transfer>
                        <Transfer>
                            <Name>TenConstant</Name>
                            <Description>...</Description>
                            <NeuralFunction>
<Type>Constant</Type>
<Parameters>
    <Name>Constant</Name>
    <Value>10</Value>
    <DataType>Double</DataType>
</Parameters>
                            </NeuralFunction>
                        </Transfer>
                        <Transfer>
                            <Name>TwentyConstant</Name>
                            <Description>...</Description>
                            <NeuralFunction>
<Type>Constant</Type>
<Parameters>
    <Name>Constant</Name>
    <Value>20</Value>
    <DataType>Double</DataType>
</Parameters>
<Links>
    <Index>0</Index>
    <Name>Pause</Name>
</Links>
                            </NeuralFunction>
                        </Transfer>
                        <Transfer>
                            <Name>Pause</Name>
                            <Description>...</Description>
                            <NeuralFunction>
<Type>Pause</Type>
<Parameters>
    <Name>ConstantRate</Name>
    <Value>true</Value>
    <DataType>Boolean</DataType>
</Parameters>
<Parameters>
    <Name>Pause</Name>
    <Value>50</Value>
    <DataType>Double</DataType>
</Parameters>
                            </NeuralFunction>
                        </Transfer>
                    </Transfers>
                </InputFunctions>
                <ReferenceFunctions>
                    <Reference>
                        <Name>AtomOffsetReference</Name>
                        <Description>...</Description>
                        <NeuralFunction>
                            <Type>Addition</Type>
                            <Links>
<Index>0</Index>
<Name>FiveConstant</Name>
                            </Links>
                            <Links>
<Index>1</Index>
<Name>EightConstant</Name>
                            </Links>
                        </NeuralFunction>
                    </Reference>
                    <Transfers>
                        <Transfer>
                            <Name>FiveConstant</Name>
                            <Description>...</Description>
                            <NeuralFunction>
<Type>Constant</Type>
<Parameters>
    <Name>Constant</Name>
    <Value>5</Value>
    <DataType>Double</DataType>
</Parameters>
                            </NeuralFunction>
                        </Transfer>
                        <Transfer>
                            <Name>EightConstant</Name>
                            <Description>...</Description>
                            <NeuralFunction>
<Type>Constant</Type>
<Parameters>
    <Name>Constant</Name>
    <Value>8</Value>
    <DataType>Double</DataType>
</Parameters>
                            </NeuralFunction>
                        </Transfer>
                    </Transfers>
                </ReferenceFunctions>
                <ErrorFunctions>
                    <Error>
                        <Name>AtomOffsetError</Name>
                        <Description>...</Description>
                        <NeuralFunction>
                            <Type>Subtract</Type>
                            <Links>
<Index>0</Index>
<Name>AtomOffsetReference</Name>
                            </Links>
                            <Links>
<Index>1</Index>
<Name>AtomOffsetInput</Name>
                            </Links>
                        </NeuralFunction>
                    </Error>
                </ErrorFunctions>
                <OutputFunctions>
                    <Output>
                        <Name>AtomOffsetOutput</Name>
                        <Description>...</Description>
                        <NeuralFunction>
                            <Type>Integration</Type>
                            <Parameters>
<Name>Slow</Name>
<Value>1000</Value>
<DataType>Double</DataType>
                            </Parameters>
                            <Parameters>
<Name>Gain</Name>
<Value>100</Value>
<DataType>Double</DataType>
                            </Parameters>
                        </NeuralFunction>
                    </Output>
                </OutputFunctions>
            </Functions>
        </Controller>
    </Layer>
</Layers>
